void addEvents() {
	events.add(new Flashes000s011());
	events.add(new Violins011s021());
	events.add(new FindMe021s026());
	events.add(new Corner026s31());
	events.add(new TakeItZone031s041());
	events.add(new LookingFor041s051());
	events.add(new LookingFor051s059());
	events.add(new Silence059s060());
	events.add(new DrumFlip(60800,0,rings.size() - 1));
	events.add(new DrumFlip(61000,1,rings.size() - 2));
	events.add(new DrumFlip(61300,2,rings.size() - 3));
	events.add(new DrumFlip(61600,3,rings.size() - 4));
	events.add(new DrumFlip(61700,4,rings.size() - 5));
	events.add(new Yell101s101());
	events.add(new WubWubStart101s102());
	events.add(new WubWub101s119());
	float d = de*2;
	int sd = 62100;
	events.add(new BassWub(new PVector(0,-d,0),sd));
	events.add(new SnareWub1(sd + (int) (mspb* 1)));
	events.add(new BassWub(new PVector(0,d,0),sd + (int) (mspb * 2)));
	events.add(new SnareWub2(sd + (int) (mspb* 3)));
	events.add(new BassWub(new PVector(d,0,0),sd + (int) (mspb * 4)));
	events.add(new SnareWub3(sd + (int) (mspb* 5)));
	events.add(new BassWub(new PVector(-d,0,0),sd + (int) (mspb * 6)));
	events.add(new SnareWub1(sd + (int) (mspb* 7)));
	events.add(new BassWub(new PVector(0,0,d),sd + (int) (mspb * 8)));
	events.add(new SnareWub3(sd + (int) (mspb* 9)));
	events.add(new BassWub(new PVector(0,d,0),sd + (int) (mspb * 10)));
	events.add(new SnareWub2(sd + (int) (mspb* 11)));
	events.add(new BassWub(new PVector(d,0,0),sd + (int) (mspb* 12)));
	events.add(new SnareWub1(sd + (int) (mspb* 13)));
	events.add(new BassWub(new PVector(-d,0,0),sd + (int) (mspb * 14)));
	events.add(new SnareWub2(sd + (int) (mspb* 15)));
	events.add(new BassWub(new PVector(0,0,d),sd + (int) (mspb * 16)));
	events.add(new SnareWub3(sd + (int) (mspb* 17)));
	events.add(new BassWub(new PVector(0,d,0),sd + (int) (mspb * 18)));
	events.add(new SnareWub2(sd + (int) (mspb* 19)));
	events.add(new BassWub(new PVector(d,0,0),sd + (int) (mspb * 20)));
	events.add(new SnareWub1(sd + (int) (mspb* 21)));
	events.add(new BassWub(new PVector(-d,0,0),sd + (int) (mspb * 22)));
	events.add(new SnareWub3(sd + (int) (mspb* 23)));
	events.add(new BassWub(new PVector(0,0,d),sd + (int) (mspb * 24)));
	events.add(new SnareWub2(sd + (int) (mspb* 25)));
	events.add(new BassWub(new PVector(0,d,0),sd + (int) (mspb * 26)));
	events.add(new SnareWub1(sd + (int) (mspb* 27)));
	events.add(new BassWub(new PVector(0,d*0.2,d),sd + (int) (mspb * 28)));
	events.add(new BassWub(new PVector(0,d*0.2,d),sd + (int) (mspb * 29)));
	events.add(new SnareWub1(sd + (int) (mspb* 29)));
	events.add(new BassWub(new PVector(0,d*0.2,d),sd + (int) (mspb * 30)));
	events.add(new SnareWub2(sd + (int) (mspb* 30)));
	events.add(new BassWub(new PVector(0,d*0.2,d),sd + (int) (mspb * 31)));
	events.add(new SnareWub2(sd + (int) (mspb* 31)));
	events.add(new StumbleDown119s121());
}